// <auto-generated />
using System;
using BooksApp.Data.Concrete.EfCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksApp.Data.Migrations
{
    [DbContext(typeof(BooksAppContext))]
    [Migration("20230522102608_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BooksApp.Entity.Concrete.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("BirthOfYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "İlber Ortaylı, Türk tarihçi, akademisyen ve yazar. Türk Tarih Kurumu Şeref Üyesidir. Ortaylı, Uluslararası Osmanlı Etütleri Komitesi yönetim kurulu üyesi ve Avrupa İranoloji Cemiyeti ve Avusturya-Türk Bilimler Forumu üyesidir.",
                            BirthOfYear = 1947,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6560),
                            FirstName = "İlber",
                            IsActive = true,
                            IsAlive = true,
                            IsDeleted = false,
                            LastName = "Ortaylı",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6600),
                            PhotoUrl = "ilber-ortayli.jpg",
                            Url = "ilber-ortayli-1"
                        },
                        new
                        {
                            Id = 2,
                            About = "Charlotte Perkins Gilman, ya da Charlotte Perkıns Stetson, önde gelen Amerikalı feminist, sosyolog, romancı, kısa hikâye, şiir ve kurmaca olmayan metinler yazarı ve sosyal reform eğitmeni. Ütopik bir feministti ve alışılmışın dışındaki konsept ve yaşam tarzından dolayı gelecek nesillere örnek teşkil etti.",
                            BirthOfYear = 1860,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6610),
                            FirstName = "Charlotte Parkins",
                            IsActive = true,
                            IsAlive = false,
                            IsDeleted = false,
                            LastName = "Gilman",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6610),
                            PhotoUrl = "charlotte-parkins-gilman.jpg",
                            Url = "charlotte-parkins-gilman-2"
                        },
                        new
                        {
                            Id = 3,
                            About = "Herbert George Wells ya da daha çok tanındığı adla H. G. Wells, Dünyaların Savaşı, Görünmez Adam, Dr. Moreau'nun Adası ve Zaman Makinesi adlı bilimkurgu romanlarıyla tanınan ama neredeyse edebiyatın her dalında birçok eser vermiş olan İngiliz yazardır. Sosyalist olduğunu açıkça söyleyen H.G. Wells'in çoğu eserinde önemli ölçüde siyasi ve sosyal yorumlar bulunmaktadır. Jules Verne gibi gelecekteki teknolojik gelişmeleri anlattığı kitaplarıyla bilimkurgu dalının öncülerinden hatta yaratıcılarından sayılmaktadır.",
                            BirthOfYear = 1866,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6610),
                            FirstName = "Herbert George",
                            IsActive = true,
                            IsAlive = false,
                            IsDeleted = false,
                            LastName = "Wells",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6610),
                            PhotoUrl = "herbert-george-wells.jpg",
                            Url = "herbert-george-wells-3"
                        },
                        new
                        {
                            Id = 4,
                            About = "Okula Essex'de gitti. Cambridge'de St. Johns College'e devam ederken Footlights tiyatro kulübünde görev aldı. Pek çok iş denedi. Hastanede hizmetlilik, inşaat işçiliği, kümes temizlikçiliği, bir Arap aile için korumalık yaptı. Daha sonra BBC'de Dr. Who dizisinde yapımcılık ve senaryo editörlüğü yaptı. Dr. Who'nun üç bölümünü yazdı. Monty Pyton grubundan Graham Chapman ile birlikte çalıştı.\r\n\r\nBBC'de yayımlanan The Hitchhiker's Guide to the Galaxy (Otostopçunun Galaksi Rehberi) adlı radyo oyunu ile ünlü oldu. Oyun, kitap olarak da yayımlandı. Bu radyo oyunundan aynı adlı bir bilgisayar oyunu da üretti. Daha sonra Bureaucracy ve Starship Titanic adlı bilgisayar oyunları üzerinde de çalıştı. Starship Titanic sonradan bir kitap olarak da yayımlandı, ancak Adams'ın hem oyun hem de kitap üzerinde çalışacak zamanı olmadığından kitabı Terry Jones yazdı. İleri derecede bir Beatles hayranıydı.",
                            BirthOfYear = 1982,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6610),
                            FirstName = "Douglas",
                            IsActive = true,
                            IsAlive = true,
                            IsDeleted = false,
                            LastName = "Adams",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6610),
                            PhotoUrl = "douglas-adams.jpg",
                            Url = "douglas-adams-4"
                        },
                        new
                        {
                            Id = 5,
                            About = "Ray Douglas Bradbury korku ve bilimkurgu tarzlarında yazan Amerikalı bir yazardır. En çok bilinen kitapları 1950'de yazdığı kısa hikâyeler kitabı ve bir roman olan The Martian Chronicles ve 1953'te yazdığı başyapıtı olan Fahrenheit 451'dir. Los Angeles'ta 91 yaşında öldü.",
                            BirthOfYear = 1920,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6620),
                            FirstName = "Ray Douglas",
                            IsActive = true,
                            IsAlive = false,
                            IsDeleted = false,
                            LastName = "Bradbury",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6620),
                            PhotoUrl = "ray-douglas-bradbury.jpg",
                            Url = "ray-douglas-bradbury-5"
                        },
                        new
                        {
                            Id = 6,
                            About = "Japon yazardır. Tsugaru Yarımadası’nın merkezi yakınlarında küçük bir kasaba olan Kanagi’de doğdu. Asıl adı Şuuci Tsuşima'dır. Ailedeki siyasetçi olma geleneğine karşı çıkarak, yazar olmaya karar verdi. Yirmi yaşında Tokyo Üniversitesi Fransız Edebiyatı Bölümü’ne kaydını yaptırdı. Hayatının büyük bölümünde esrarkeş, veremli, asabi, kavgacı ve alkolik biri olarak birkaç kez intihar etmeye kalkıştı. Dazai, 1948’de metresiyle birlikte suya atlayarak intihar etti. Ölümünün üzerinden bunca sene geçmesine rağmen, Japonya’da hâlâ ilgi gören bir yazardır. Eserlerinin çoğunluğunda yalnızlığı ele alır. Yalnızlık ön planda iken insanın arayış içinde olması ve insanın varoluşunu, içe dönüklüğünü yani temelde insanı ele alır.",
                            BirthOfYear = 1909,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6620),
                            FirstName = "Osamu",
                            IsActive = true,
                            IsAlive = false,
                            IsDeleted = false,
                            LastName = "Dazai",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6620),
                            PhotoUrl = "osamu-dazai.jpg",
                            Url = "osamu-dazai-6"
                        },
                        new
                        {
                            Id = 7,
                            About = "Eric Arthur Blair veya daha bilinen takma adıyla George Orwell 20. yüzyıl İngiliz edebiyatının önde gelen kalemleri arasında yer alan İngiliz romancı, gazeteci ve eleştirmen. En çok, dünyaca ünlü Bin Dokuz Yüz Seksen Dört adlı romanı ve bu romanda yarattığı Big Brother kavramı ile tanınır. ",
                            BirthOfYear = 1903,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6620),
                            FirstName = "George",
                            IsActive = true,
                            IsAlive = false,
                            IsDeleted = false,
                            LastName = "Orwell",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6620),
                            PhotoUrl = "george-orwell.jpg",
                            Url = "george-orwell-7"
                        },
                        new
                        {
                            Id = 8,
                            About = "Matt Haig bir İngiliz yazar ve gazetecidir. Çocuklar ve yetişkinler için, genellikle spekülatif kurgu türünde hem kurgu hem de kurgu olmayan kitaplar yazmıştır. Haig, çocuklar ve yetişkinler için hem kurgu hem de kurgu olmayan kitapların yazarıdır. Kurgusal olmayan çalışması Reasons to Stay Alive , Sunday Times'ın en çok satanlar listesinde bir numaraydı ve 46 hafta boyunca Birleşik Krallık'ta ilk 10'da yer aldı. En çok satan çocuk romanı 'Noel Baba ve Ben' şu anda filme uyarlanıyor, yapımcılığını StudioCanal ve Blueprint Pictures üstleniyor.",
                            BirthOfYear = 1982,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6630),
                            FirstName = "Matt",
                            IsActive = true,
                            IsAlive = true,
                            IsDeleted = false,
                            LastName = "Haig",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6630),
                            PhotoUrl = "matt-haig.jpeg",
                            Url = "matt-haig-8"
                        },
                        new
                        {
                            Id = 9,
                            About = "Stephen William Hawking, İngiliz fizikçi, kozmolog, astronom, teorisyen ve yazar. Stephen Hawking, Einstein'dan bu yana dünyaya gelen en parlak teorik fizikçi olarak kabul edilmektedir. 12 onur derecesi almıştır. 1982'de CBE ile ödüllendirilmiş, bundan başka birçok madalya ve ödül almıştır. ",
                            BirthOfYear = 1942,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6630),
                            FirstName = "Stephen William",
                            IsActive = true,
                            IsAlive = false,
                            IsDeleted = false,
                            LastName = "Hawking",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6630),
                            PhotoUrl = "stephen-william-hawking.jpg",
                            Url = "stephen-william-hawking-9"
                        },
                        new
                        {
                            Id = 10,
                            About = "Fyodor Mihayloviç Dostoyevski, Rus roman yazarıdır. Çocukluğunu sarhoş bir baba ve hasta bir anne arasında geçiren Dostoyevski, annesinin ölümünden sonra Petersburg'daki Mühendis Okulu'na girdi. Babasının ölüm haberini de burada aldı. Okulu başarıyla bitirdikten sonra istihkâm bölüğüne girdi.",
                            BirthOfYear = 1821,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6630),
                            FirstName = "Fyodor",
                            IsActive = true,
                            IsAlive = false,
                            IsDeleted = false,
                            LastName = "Dostoyevski",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6630),
                            PhotoUrl = "fyodor-dostoyevski.jpg",
                            Url = "fyodor-dostoyevski-10"
                        },
                        new
                        {
                            Id = 11,
                            About = "Manon Steffan Ros, Galli bir romancı, oyun yazarı, oyun yazarı, senarist ve müzisyendir. Tamamı Galce olan yirmiden fazla çocuk kitabı ve yetişkinler için üç romanın yazarıdır. Ödüllü romanı Blasu, The Seasoning başlığı altında İngilizce'ye çevrildi.",
                            BirthOfYear = 1983,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6640),
                            FirstName = "Manon Steffan",
                            IsActive = true,
                            IsAlive = true,
                            IsDeleted = false,
                            LastName = "Ros",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6640),
                            PhotoUrl = "manon-steffan-ros.jpg",
                            Url = "manon-steffan-ros-11"
                        },
                        new
                        {
                            Id = 12,
                            About = "Mustafa Kemal Atatürk, Türk asker ve devlet adamıdır. Türk Kurtuluş Savaşı'nın başkomutanı, Türkiye Cumhuriyeti'nin kurucusu ve ilk cumhurbaşkanıdır.Atatürk; çağdaş, ilerici ve laik bir ulus devlet kurmak için siyasal, ekonomik ve kültürel alanlarda sekülarist ve milliyetçi nitelikte yenilikler gerçekleştirdi. Yabancılara tanınan ekonomik ayrıcalıklar kaldırıldı ve onlara ait üretim araçları ve demir yolları millîleştirildi. Tevhîd-i Tedrîsât Kanunu ile eğitim, Türk hükûmetinin denetimine girdi. Seküler ve bilimsel eğitim esas alındı. Binlerce yeni okul yapıldı. İlköğretim ücretsiz ve zorunlu duruma getirildi. Yabancı okullar devlet denetimine alındı. Köylülerin sırtına yüklenen ağır vergiler azaltıldı. Erkeklerin serpuşlarında ve giysilerinde bazı değişiklikler yapıldı. Takvim, saat ve ölçülerde değişikliklere gidildi. Mecelle kaldırılarak yerine seküler Türk Kanunu Medenisi yürürlüğe konuldu. Kadınların sivil ve siyasal hakları pek çok Batı ülkesinden önce tanındı. Çok eşlilik yasaklandı. Kadınların tanıklığı ve miras hakkı, erkeklerinkiyle eşit duruma getirildi. Benzer olarak, dünyanın çoğu ülkesinden önce olarak Türkiye'de kadınlara ilkin yerel seçimlerde (1930), sonra genel seçimlerde (1934) seçme ve seçilme hakkı tanındı. Ceza ve borçlar hukukunda seküler yasalar yürürlüğe konuldu. Sanayi Teşvik Kanunu kabul edildi. Toprak reformu için çabalandı. Arap harfleri temelli Osmanlı alfabesinin yerine Latin harfleri temelli yeni Türk alfabesi kabul edildi. Halkı okuryazar kılmak için eğitim seferberliği başlatıldı. Üniversite Reformu gerçekleştirildi. Birinci Beş Yıllık Sanayi Planı yürürlüğe konuldu. Sınıf ve durum ayrımı gözeten lakap ve unvanlar kaldırıldı ve soyadları yürürlüğe konuldu. Bağdaşık ve birleşmiş bir ulus yaratılması için Türkleştirme siyaseti yürütüldü.",
                            BirthOfYear = 1881,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6640),
                            FirstName = "Mustafa Kemal",
                            IsActive = true,
                            IsAlive = false,
                            IsDeleted = false,
                            LastName = "Atatürk",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6640),
                            PhotoUrl = "mustafa-kemal-ataturk.jpg",
                            Url = "mustafa-kemal-ataturk-12"
                        },
                        new
                        {
                            Id = 13,
                            About = "Yuval Noah Harari, İsrailli tarihçi ve yazardır. İsrailli bir kamu entelektüeli, tarihçi ve Kudüs İbrani Üniversitesi Tarih Bölümü'nde profesör. Popüler bilim en çok satan kitapları Sapiens: İnsanlığın Kısa Tarihi, Homo Deus: Yarının Kısa Tarihi ve 21.Yüzyıl İçin 21 Ders kitabının yazarıdır.",
                            BirthOfYear = 1976,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6640),
                            FirstName = "Yuval Noah",
                            IsActive = true,
                            IsAlive = true,
                            IsDeleted = false,
                            LastName = "Harari",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6640),
                            PhotoUrl = "yuval-noah-harari.jpg",
                            Url = "yuval-noah-harari-13"
                        },
                        new
                        {
                            Id = 14,
                            About = "Rus yazar ve asker. Dünya tarihinin en iyi yazarlarından birisi olarak bilinmektedir. Tolstoy, zengin bir ailenin çocuğu olarak Rusya'nın Tula şehrindeki Yasnaya Polyana adlı bir konakta doğdu. Çok küçük yaşlarında önce annesini, sonra babasını kaybetti; yakınlarının elinde büyüdü. Çocukluğundan beri gerçekleri incelemeye karşı büyük bir ilgisi vardı. Fransızcasını ilerletmiş, Voltaire'i ve Jean-Jacques Rousseau'yu okumuş, bu iki yazarın kuvvetli etkisinde kalmıştı. Daha sonraları Yasnaya Polyana'ya dönen Tolstoy, yoksul köylülerin arasına katıldı. İlk eseri olan 'Çocukluk'u bu sıralarda yazdı.",
                            BirthOfYear = 1828,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6640),
                            FirstName = "Lev Nikolayeviç",
                            IsActive = true,
                            IsAlive = false,
                            IsDeleted = false,
                            LastName = "Tolstoy",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6650),
                            PhotoUrl = "lev-nikolayevic-tolstoy.jpg",
                            Url = "lev-nikolayevic-tolstoy-14"
                        },
                        new
                        {
                            Id = 15,
                            About = "Afşin Kum Kimdir? Afşin Kum, 1972 İzmir doğumlu. Boğaziçi Üniversitesinde bilgisayar mühendisliği, Bilgi Üniversitesinde sinema-televizyon öğrenimi gördü. 1997'den bu yana çeşitli kurumlarda yazılımcı ve yönetici olarak çalıştı.",
                            BirthOfYear = 1972,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6650),
                            FirstName = "Afşin",
                            IsActive = true,
                            IsAlive = true,
                            IsDeleted = false,
                            LastName = "Kum",
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 111, DateTimeKind.Local).AddTicks(6650),
                            PhotoUrl = "afsin-kum.jpg",
                            Url = "afsin-kum-15"
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EditionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EditionYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "'… İyi geceler. Ben prensi olmayan bir Külkedisi’yim. Tokyo’nun neresinde olduğumu biliyor musunuz? Beni bir daha görmeyeceksiniz.'\r\n\r\nYirminci yüzyıl Japon edebiyatının önde gelen yazarlarından, sıradışı hayatıyla da meşhur Osamu Dazai, savaş sonrası Japonya’sının edebiyat çevrelerince tanınmasını sağlayan, kaleme aldığı ilk eserlerden Öğrenci Kız’da Tokyo’nun banliyösünde yaşayan bir genç kızın on iki saatini ironik ve hünerli bir üslupla kaleme alıyor.\r\n\r\nİsimsiz genç kızın, nefret ettiği sabahlardan birine gözlerini açmasıyla başlayıp gece yatağa yattığı anda biten kısa romanda Dazai, artık yitmiş bir dönemin yaygın toplumsal normlarına karşı bireyin duyduğu huzursuzluğu, gençliğin ilk buhranları ve asiliğiyle birleştiriyor. \r\n\r\nÖğrenci Kız, Dazai’nin sonraki çoğu eserinde yer bulacak aykırı kişiliklerin ilk örneklerinden birini görmeyi ve yazarın zihninin derinliklerine yakından bakmayı sağlayacak bir klasik.",
                            AuthorId = 6,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(740),
                            EditionNumber = 4,
                            EditionYear = 2022,
                            ImageUrl = "ogrenci-kiz.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(740),
                            Name = "Öğrenci Kız",
                            PageCount = 439,
                            Price = 90m,
                            PublisherId = 1,
                            Stock = 4,
                            Url = "ogrenci-kiz-1"
                        },
                        new
                        {
                            Id = 2,
                            About = "Hayvanlardan Tanrılara: Sapiens kitabıyla insan türünün dünyaya nasıl egemen olduğunu anlatan Harari, Homo Deus’ta çarpıcı öngörüleriyle yarınımızı ele alıyor. İnsanlığın ölümsüzlük, mutluluk ve tanrısallık peşindeki yolculuğunu bilim, tarih ve felsefe ışığında incelediği bu çalışmasında, insanın bambaşka bir türe, Homo deus’a evrildiği bir gelecek kurguluyor.\r\n\r\nYola *önemsiz bir hayvan* olarak çıkan Homo sapiens, tanrılar katına ulaşmak uğruna kendi sonunu mu hazırlıyor?\r\n\r\nHomo sapiens nasıl oldu da evrenin insan türünün etrafında döndüğünü iddia eden hümanist öğretiye inandı?\r\n\r\nBu öğreti gündelik yaşantımızı, sanatımızı ve en gizli tutkularımızı nasıl şekillendiriyor?\r\n\r\nİnsanı inekler, tavuklar, şempanzeler ve bilgisayar programlarının tümünden ayıran yüksek zekası ve kudreti dışında herhangi bir alametifarikası var mı?\r\n\r\nTarih boyunca benzeri görülmemiş kazanımlar elde etmemize rağmen mutluluk seviyemizde neden kayda değer bir artış olmadı?\r\n\r\n*Tüm bunları anlamak için tek yapmamız gereken geriye dönüp bakmak ve Homo sapiens’in aslında ne olduğunu, hümanizmin nasıl dünyaya hakim bir din hâline geldiğini ve hümanizm rüyasını gerçekleştirmeye çalışmanın aslında neden insanlığın kendi sonunu getireceğini incelemektir. İşte bu kitabın temel meselesi budur.*\r\n\r\n*Okurken hem eğlenecek hem de çok şaşıracaksınız. Her şeyin ötesinde, kendinizi daha önce hiç düşünmediğiniz şeyleri düşünürken bulacaksınız.*\r\n\r\n- Daniel Kahneman, Hızlı ve Yavaş Düşünme’nin yazarı\r\n\r\n*Homo Deus’u okuduğunuzda uzun ve zorlu bir yolculuğun ardından vardığınız bir uçurumun kenarında durduğunuzu hissedeceksiniz. Yolculuğun artık bir önemi kalmayacak, çünkü bir sonraki adımınızı engin bir boşluğa atacaksınız.*",
                            AuthorId = 13,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(760),
                            EditionNumber = 12,
                            EditionYear = 2021,
                            ImageUrl = "homo-deus-yarinin-kisa-bir-tarihi.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(760),
                            Name = "Homo Deus: Yarının Kısa Bir Tarihi",
                            PageCount = 308,
                            Price = 60m,
                            PublisherId = 1,
                            Stock = 28,
                            Url = "homo-deus-yarinin-kisa-bir-tarihi-2"
                        },
                        new
                        {
                            Id = 3,
                            About = "Edebiyat tarihinin ilk distopyası olan Efendi Uyanıyor bir 19. yy. centilmeni olan Graham’ın öyküsünü anlatıyor. Nadir görülen bir uykusuzluk hastalığından mustarip olan Graham en sonunda uyumayı başarır. Ne var ki bu kez 200 yıllık trans halinde bir uykuya dalacaktır. Uyandığında ise, banka hesabına işleyen faizler sayesinde dünyanın en zengin ve en güçlü adamı olduğunu öğrenir. O artık bambaşka ve hiç tanımadığı bir dünyada yaşamaktadır. Dünyanın tek efendisi ve sahibi odur! Graham uyuduğu sırada servetini idare eden Konsey, tüm gezegene hüküm süren son derece karanlık ve acımasız bir sistem kurmuştur. Oysa insanların bir kurtarıcı olarak gördüğü Graham’dan beklenen, toplumu bu korkunç despotlardan kurtarmasıdır. Bir distopya klasiği ve politik bilimkurgu türünün en iyi örneklerinden biri olan Wells’in bu başyapıtı, okuru fantastik bir maceraya sürüklüyor. Günümüzden 114 yıl önce yazılmış olmasına rağmen global şirketlerin yükselişi, uçakların seyahat amaçlı kullanımı ve birçok teknolojik gelişmeyi zamanının çok ötesinde başarılı bir şekilde tahmin etmiş olması şaşkınlık yaratıyor. Geleceğe dair yerinde tahminlerinin yanı sıra toplumsal adaletsizlikle boğuşan bir dünyayı tasvir eden Efendi Uyanıyor, distopya, bilim kurgu ve politik roman hayranları için mükemmel bir seçim. \"Wells’in en çarpıcı yönü, edebiyatın klişeleşmiş yanlarına yeni bir soluk getirip canlılık katması...\" -The Spectator- \"Politik bilim-kurgu ve distopya severler için kaçırılmaması gereken bir eser...\" -Times Literary Supplement-",
                            AuthorId = 3,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(760),
                            EditionNumber = 2,
                            EditionYear = 2019,
                            ImageUrl = "efendi-uyaniyor.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(760),
                            Name = "Efendi Uyanıyor",
                            PageCount = 417,
                            Price = 85m,
                            PublisherId = 1,
                            Stock = 39,
                            Url = "efendi-uyaniyor-3"
                        },
                        new
                        {
                            Id = 4,
                            About = "Milliways Öğlen Menüsü, editörünün iznini alarak, Otostopçunun Galaksi Rehberi’nden bir pasaj aktarmaktaydı. Pasaj şöyleydi: Belli başlı her galaktik uygarlığın tarihi üç ayrı ve fark edilebilir aşamadan geçme eğilimindedir. Bu aşamalar Hayatta Kalma, Sorgulama ve İncelikli Düşünmedir; bir başka deyişle Nasıl, Neden ve Nerede aşamaları olarak da bilinirler. Örneğin, ilk aşama Nasıl Yiyebiliriz? sorusuyla, ikinci aşama Neden Yiyoruz? sorusuyla, üçüncü aşamaysa Öğle Yemeğini Nerede Yiyelim? sorusuyla tanımlanmaktadır.\r\n\r\nMenü daha sonra Milliways’in, Evrenin Sonundaki Restoran’ın bu üçüncü soruya çok uygun ve seçkin bir cevap olduğunu söylüyordu.\r\n\r\nAltın Kalp’in yolcuları sabahtan itibaren altı tamamen imkânsız işi başarmışken, günü gerçekten layık olduğu bir şekilde taçlandırmaya karar vermişlerdi: Gidilebilecek en iyi restoranda, seyredilebilecek en iyi manzaraya karşı mükellef bir yemek.\r\n\r\nBu arada gidiyoruz, ama aranızda rezervasyon yaptıran oldu mu?",
                            AuthorId = 4,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(770),
                            EditionNumber = 9,
                            EditionYear = 2018,
                            ImageUrl = "evrenin-sonundaki-restoran.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(770),
                            Name = "Evrenin Sonundaki Restoran",
                            PageCount = 444,
                            Price = 90m,
                            PublisherId = 2,
                            Stock = 13,
                            Url = "evrenin-sonundaki-restoran-4"
                        },
                        new
                        {
                            Id = 5,
                            About = "Ray Bradbury sadece bilimkurgunun değil fantastik edebiyatın ve korkunun da yirminci yüzyıldaki ustalarından biri. Bilimkurgunun *iyi edebiyat* da olabileceğini kanıtlayan belki de ilk yazar. Yayımlandığı anda klasikleşen, distopya edebiyatının dört temel kitabından biri olan Fahrenheit 451 ise bir yirminci yüzyıl başyapıtı.\r\n\r\nGuy Montag bir itfaiyeciydi. Televizyonun hüküm sürdüğü bu dünyada kitaplar ise yok olmak üzereydi zira itfaiyeciler yangın söndürmek yerine ortalığı ateşe veriyordu. Montag’ın işi ise yasadışı olanların en tehlikelisini yakmaktı: Kitapları.\r\n\r\nMontag yaptığı işi tek bir gün dahi sorgulamamıştı ve tüm gününü televizyonla kaplı odalarda geçiren eşi Mildred’la beraber yaşıyordu. Ancak yeni komşusu Clarisse’le tanışmasıyla tüm hayatı değişti. Kitapların değerini kavramaya başlayan Montag artık tüm bildiklerini sorgulayacaktı.\r\n\r\nİnsanların uğruna canlarını feda etmeyi göze aldığı bu kitapların içinde ne vardı?\r\nGerçeklerin farkına vardıktan sonra bu karanlık toplumda artık yaşanabilir miydi?\r\n\r\nFahrenheit 451, yeryüzünde tek bir kitap kalacak olsa, o kitap olmaya aday.",
                            AuthorId = 6,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(770),
                            EditionNumber = 4,
                            EditionYear = 2022,
                            ImageUrl = "fahrenheit-451.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(770),
                            Name = "Fahrenheit 451",
                            PageCount = 307,
                            Price = 60m,
                            PublisherId = 1,
                            Stock = 28,
                            Url = "fahrenheit-451-5"
                        },
                        new
                        {
                            Id = 6,
                            About = "1984 kitabı, İngiliz filozof ve yazar George Orwell tarafından kaleme alınmış, 1984 kitap konusu olarak 20. yüzyılın en önemli distopya örneklerinden biri olmuştur. George Orwell, 1948 yılında tamamladığı ve geleceğe dair karamsar bir kurgu geliştirerek gelecek hakkında insanlığı uyarmayı amaçlamıştır. Egemen sınıfa dayalı, totaliter, baskıcı bir yönetim anlayışının benimsendiği üç ayrı devletin egemenliğindeki siyasal düzenden bahsetmektedir. 1984 kitabı, günümüz ile geçmiş arasında gerçekçi bir benzerliklere dayandıran, dönemin okurlarını düşündürtüp hayal güçlerinin sınırlarını zorlamayı sağlayan distopik, alegorik, politik bir romandır.",
                            AuthorId = 7,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(780),
                            EditionNumber = 2,
                            EditionYear = 2022,
                            ImageUrl = "bindokuzyuzseksendort-1984.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(780),
                            Name = "1984",
                            PageCount = 485,
                            Price = 95m,
                            PublisherId = 3,
                            Stock = 16,
                            Url = "bindokuzyuzseksendort-1984-6"
                        },
                        new
                        {
                            Id = 7,
                            About = "H. G. Wells, bilimkurgunun atası, türe adını altın harflerle yazdırmış en büyük yazarlardan. Yazdığı bilim fantazileri nesiller boyu yazarları etkilemiş, onlara yol göstermiş; ilk basıldıkları dönemden itibaren etkilerini yitirmeden okurların gönlünde taht kurmaya devam etmiştir. Görünmez Adam da Wells’in eserleri içinde en akılda kalıcı olanlardan biri.\r\n\r\nTuhaf görünüşlü yabancı, bir tipi sırasında Iping Köyü’ne gelir. Garip hareketleri, giyinişi, suratının tamamının bandajlar içinde olması ve gözlüklerini bir an olsun gözünden çıkarmaması köy sakinleri tarafından kimi zaman şüpheyle, kimi zaman düşmanca karşılanır. Kısa süre içerisinde hakkındaki dedikodular giderek yoldan çıkan bir dizi olaya neden olacaktır.",
                            AuthorId = 3,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(780),
                            EditionNumber = 6,
                            EditionYear = 2021,
                            ImageUrl = "gorunmez-adam.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(780),
                            Name = "Görünmez Adam",
                            PageCount = 139,
                            Price = 55m,
                            PublisherId = 1,
                            Stock = 19,
                            Url = "gorunmez-adam-7"
                        },
                        new
                        {
                            Id = 8,
                            About = "Hayvan Çiftliği ya da orijinal ismiyle \"Animal Farm\", Eric Arthur Blair yani kitaplarını yazarken kullandığı ismiyle George Orwell’in mecazi bir dille kaleme aldığı ve ilk kez 1945 yılında Birleşik Krallık’ta yayımlan, 1996 tarihinde de Retro Hugo Ödülü’nü kazanan, fabl tarzındaki siyasi hiciv romanıdır. Stalinizmin eleştirildiği \"Hayvan Çiftliği\" romanı, SSCB’nin kuruluşundan itibaren meydana gelen önemli olayları kara mizah yoluyla anlatmaktadır. Yayımlandığında büyük bir ilgi uyandıran bu eser 1954 ve 1999 yıllarında filme uyarlanmış, Pink Floyd’un Animals albümüne ilham olmuştur. George Orwell’in tarihsel bir gerçeği eleştirdiği “Hayvan Çiftliği” eseri, Türkçeye ilk kez 1954 yılında çevrilmiştir.\r\n\r\nGeorge Orwell (25 Haziran 1903 - 21 Ocak 1950), asıl ismi Eric Arthur Blair olan ve oluşturduğu Big Brother (Büyük Birader) kavramı ile tanınan, gazetecilik ve eleştirmenlik de yapmış 20. yüzyıl İngiliz edebiyatının önde gelen yazarıdır. Kaleme aldığı eserleri birçok dile çevrilen, çağdaş klasikler arasında gösterilen George Orwell, “Hayvan Çiftliği” eserinde bir devrimin trajedisini dile getirmiştir.",
                            AuthorId = 7,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(780),
                            EditionNumber = 14,
                            EditionYear = 2021,
                            ImageUrl = "hayvan-ciftligi.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(780),
                            Name = "Hayvan Çiftliği",
                            PageCount = 99,
                            Price = 45m,
                            PublisherId = 3,
                            Stock = 26,
                            Url = "hayvan-ciftligi-8"
                        },
                        new
                        {
                            Id = 9,
                            About = "Bir hedef bulacaksınız, o uğurda çalışacaksınız, hedefinizi gerçekleştirmek için bir yol arayacaksınız, yol yoksa da o yolu yapacaksınız. Bir defa geçtiğiniz yoldan da bir daha geri dönmeyeceksiniz. Çünkü lüzumsuz geri dönüş başarısızlıktır, tekrara düşmektir, ufku kapatmaktır. Hedef bulmak, yol açmak ve aynı yoldan geri dönmemek… Hayattaki gayemiz budur.",
                            AuthorId = 1,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(790),
                            EditionNumber = 2,
                            EditionYear = 2022,
                            ImageUrl = "insan-gelecegini-nasil-kurar.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(790),
                            Name = "İnsan Geleceğini Nasıl Kurar",
                            PageCount = 420,
                            Price = 119m,
                            PublisherId = 7,
                            Stock = 13,
                            Url = "insan-gelecegini-nasil-kurar-9"
                        },
                        new
                        {
                            Id = 10,
                            About = "*Bu satırları okuyanlarınızın büyük çoğunluğunun, insanların bir mitten ibaret olduğuna inandığını biliyorum ama ben size onların gerçekten var olduklarını bildirmek üzere buradayım. Bilmeyenler için söyleyeyim, insan dediğimiz şey orta zekâlı ve iki ayaklı bir yaşam formu; evrenin çok ıssız bir köşesinde yer alan küçük ve sulu bir gezegende, büyük ölçüde yanılsamalarla dolu bir varoluş sürdürüyor.*\r\n\r\nYağmurlu bir akşamda Profesör Andrew Martin, önce dünyanın en büyük matematik bilmecesini çözmeyi başarıyor, ardından sırra kadem basıyor. Nihayet bir yol kenarında çırılçıplak halde bulunduğunda, kıyafetsizlikten daha ciddi bir meselesi olduğu ortaya çıkıyor: Andrew Martin artık insanlardan tiksiniyor; görünüşlerinden de yiyip içtiklerinden de bitmeyen şiddet ve savaş arzularından da... Yabancı bir tür arasında kaybolmuş hissediyor kendini. Sevgi ve aile kavramları onda şaşırtıcı bir ilgi uyandırsa da tüm sakinlerinden nefret ediyor bu gezegenin. Newton hariç... Ama o da bir köpek işte...",
                            AuthorId = 8,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(790),
                            EditionNumber = 4,
                            EditionYear = 2022,
                            ImageUrl = "insanlar.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(790),
                            Name = "İnsanlar",
                            PageCount = 216,
                            Price = 75m,
                            PublisherId = 5,
                            Stock = 40,
                            Url = "insanlar-10"
                        },
                        new
                        {
                            Id = 11,
                            About = "Charlotte Perkins Gilman yaşadığı dönemin önde gelen hümanistlerinden ve kadın hakları savunucularından biri olmasının yanında feminist edebiyatın en önemli erken dönem temsilcilerinden. Yazıldıktan yaklaşık 65 sene sonra kitap formatında yayımlanabilen Kadınlar Ülkesi ise feminist ütopyanın ilk örneklerinden.\r\n\r\nBirinci Dünya Savaşı’nın arifesinde üç Amerikalı erkek pek fazla insanın bulunmadığı, ücra bir yerde, tamamen kadınlardan oluşan bir topluluğa denk gelir. Gözlerine inanamayan kâşifler bu topraklarda erkeklerin de olması gerektiğine dair inançlarıyla araştırmalarına başlar.\r\n\r\nÇok geçmeden bu gizemli ülke ile ilgili gerçekler bir bir açığa çıksa da misafirlerin merakı giderilmenin aksine daha da artar ve Kadınlar Ülkesi’nin yönetim biçiminden inançlarına, kültüründen ekonomisine ve hatta anneliğe kadar pek çok konuda bilgi sahibi olmaya ve toplumsal cinsiyet rollerini sorgulamaya başlarlar.\r\n\r\nToplumsal roller cinsiyete göre belirlenebilir mi? Kadınlık ve erkeklik değişmez kavramlar mıdır?\r\n\r\nKadınlar Ülkesi, ataerkilliğe verilmiş nüktedan bir yanıt.",
                            AuthorId = 2,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(800),
                            EditionNumber = 3,
                            EditionYear = 2022,
                            ImageUrl = "kadinlar-ulkesi.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(800),
                            Name = "Kadınlar Ülkesi",
                            PageCount = 315,
                            Price = 65m,
                            PublisherId = 1,
                            Stock = 25,
                            Url = "kadinlar-ulkesi-11"
                        },
                        new
                        {
                            Id = 12,
                            About = "2016 yılının BBC Reith derslerinde Stephen Hawking, bütün bir ömür süren araştırmalarını on beş dakika içinde aktarma gibi gerçekten zorlu bir meydan okumayı kabul etti. Bu çok kısa süren derslerde Hawking, evrenin gizemlerini ortaya sererken, kara delikleri anladığımız takdirde uzayzamanın sırlarına erişebileceğimizi vurguluyor.",
                            AuthorId = 6,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(800),
                            EditionNumber = 4,
                            EditionYear = 2022,
                            ImageUrl = "kara-delikler.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(800),
                            Name = "Kara Delikler",
                            PageCount = 439,
                            Price = 90m,
                            PublisherId = 1,
                            Stock = 4,
                            Url = "kara-delikler-12"
                        },
                        new
                        {
                            Id = 13,
                            About = "\"Kumarbaz\" tüm varlığını, gücünü, yeteneğini rulet masasına yatıran; bilinmeyene, tehlikeye özlem duyan; hem başkaldıran, hem korkan; içinde binbir türlü çelişki barındıran kumara tutkun bir adamın romanı. Kendisi de bir süre kumarın tutsağı olan Dostoyevski, belki hiçbir romanına kendi yaşamından bu kadar çok şey katmamıştır. Hiçbir şey yazmasaydı bile \"Kumarbaz\" onu Dostoyevski yapmaya yeterdi.",
                            AuthorId = 10,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(810),
                            EditionNumber = 14,
                            EditionYear = 2020,
                            ImageUrl = "kumarbaz.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(810),
                            Name = "Kumarbaz",
                            PageCount = 417,
                            Price = 85m,
                            PublisherId = 6,
                            Stock = 10,
                            Url = "kumarbaz-13"
                        },
                        new
                        {
                            Id = 14,
                            About = " “Son” denilen nükleer felaketten sonra anne ve oğul arasında kurulan geçmişi ve o günü kapsayan ancak sınırları olan bir ilişkinin kapısından içeri girerken; ilacın, elektriğin, kalabalığın, cep telefonlarının ve günümüze ait hiçbir gerecin olmadığı bir dünyaya adım atacaksınız. Hayatta kalma güdüsü, yalnızlık\r\nve ölüm temalarıyla öne çıkan, Galceye özgü akıcı ve güçlü tasvirlerle ilerleyen Nebo’nun Mavi Kitabı; günümüz insanının doğadan ne kadar kopuk yaşadığını da  gözler önüne seriyor.\r\n \r\nManon Steffan Ros “ekolojik distopya” temeline dayanan,\r\nödüllü ve çoksatan romanında, insanın hayatta kalma içgüdüsüyle birlikte, çağdaş dünya düzenini de sorguluyor.",
                            AuthorId = 11,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(810),
                            EditionNumber = 12,
                            EditionYear = 2021,
                            ImageUrl = "nebonun-mavi-kitabi.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(810),
                            Name = "Nebo'nun Mavi Kitabı",
                            PageCount = 582,
                            Price = 115m,
                            PublisherId = 7,
                            Stock = 29,
                            Url = "nebonun-mavi-kitabi-14"
                        },
                        new
                        {
                            Id = 15,
                            About = "Ey Türk gençliği! Birinci görevin, Türk bağımsızlığını, Türk Cumhuriyeti’ni sonsuza kadar korumak ve savunmaktır. Varlığının ve geleceğinin tek temeli budur. Bu temel, senin en değerli hazinendir. Gelecekte de, seni bu hazineden yoksun bırakmak isteyecek iç ve dış düşmanların olacaktır. Bir gün, bağımsızlık ve cumhuriyeti savunma zorunluluğuna düşersen, göreve atılmak için, içinde bulunacağın durumun olanak ve koşullarını düşünmeyeceksin!",
                            AuthorId = 12,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(810),
                            EditionNumber = 36,
                            EditionYear = 2022,
                            ImageUrl = "nutuk.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(810),
                            Name = "Nutuk",
                            PageCount = 332,
                            Price = 65m,
                            PublisherId = 8,
                            Stock = 34,
                            Url = "nutuk-15"
                        },
                        new
                        {
                            Id = 16,
                            About = "Çoğu çalışma insanlığın serüvenini ya tarihi ya da biyolojik bir yaklaşımla ele alır, ancak Harari 70 bin yıl önce gerçekleşen Bilişsel Devrim’le başlattığı bu kitabında gelenekleri yerle bir ediyor. İnsanların küresel ekosistemde oynadıkları rolden imparatorlukların yükselişine ve modern dünyaya kadar pek çok konuyu irdeleyen Sapiens, tarihle bilimi bir araya getirerek kabul görmüş anlatıları yeniden ele alıyor. Harari ayrıca geleceğe bakmaya da zorluyor okuru. Yakın zamanda insanlar, dört milyar yıldır yaşama hükmeden doğal seçilim yasalarını esnetmeye başladılar. Artık sadece dünyayı değil, kendimizi ve diğer canlıları tasarlama becerisi de kazandık. Peki bu bizi nereye götürüyor, bizi neye dönüştürebilir?",
                            AuthorId = 13,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(820),
                            EditionNumber = 11,
                            EditionYear = 2022,
                            ImageUrl = "hayvanlardan-tanrilara-sapiens.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(820),
                            Name = "Hayvanlardan Tanrılara Sapiens",
                            PageCount = 639,
                            Price = 160m,
                            PublisherId = 1,
                            Stock = 32,
                            Url = "hayvanlardan-tanrilara-sapiens-16"
                        },
                        new
                        {
                            Id = 17,
                            About = "Savaş ve Barış, gençlere dünya klasiklerini tanıtarak, onları bu eserleri okumaya yönlendirmek amacıyla hazırladığımız Arkadaş Dünya Klasikleri Gençlik Özet Dizisi’nin üçüncü kitabıdır. Genç okurların kolayca anlayarak beğeniyle okuyabileceği yalın bir Türkçeyle orijinal metinden uyarlanmıştır.\r\n\r\nTolstoy’un başyapıtı olan Savaş ve Barış, dünya edebiyatının en önemli eserlerindendir ve Milli Eğitim Bakanlığınca 100 Temel eser kapsamında öğrencilere tavsiye edilmiştir.",
                            AuthorId = 14,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(820),
                            EditionNumber = 12,
                            EditionYear = 2022,
                            ImageUrl = "savas-ve-baris.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(820),
                            Name = "Savaş ve Barış",
                            PageCount = 239,
                            Price = 85m,
                            PublisherId = 9,
                            Stock = 14,
                            Url = "savas-ve-baris-14"
                        },
                        new
                        {
                            Id = 18,
                            About = "Kaç Ömür Gerek, Yaşamayı Öğrenmek İçin?\r\n\r\nTom Hazard’ın tehlikeli bir sırrı var. 41 yaşında sıradan bir tarih öğretmeni gibi göru¨nse de nadir rastlanan bir hastalık yu¨zu¨nden aslında yu¨zyıllardır hayatta. Shakespeare’le aynı sahnede yer almış, Kaptan Cook’la açık denizleri fethetmiş, Fitzgerald’larla içki içmiş. Ama şimdi, tek istediği normal bir hayat su¨rmek. Kimliğini değiştirmeye devam ettiği su¨rece geçmişini geride bırakabilir ve hayatta kalabilir.\r\n\r\nYapmaması gereken tek bir şey var, aşık olmak.",
                            AuthorId = 8,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(820),
                            EditionNumber = 3,
                            EditionYear = 2021,
                            ImageUrl = "zamani-durdurmanin-yollari.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(820),
                            Name = "Zamanı Durdurmanın Yolları",
                            PageCount = 329,
                            Price = 80m,
                            PublisherId = 5,
                            Stock = 5,
                            Url = "zamani-durdurmanin-yollari-15"
                        },
                        new
                        {
                            Id = 19,
                            About = "*Yaşamla ölüm arasında bir kütüphane var,* dedi. *Bu kütüphanedeki raflar sonsuza kadar gider.  Her kitap yaşamış olabileceğin başka bir hayatı yaşama şansını sunar sana. Farklı seçimler yapmış olsan, şu an nasıl bir hayatın olacağını görürsün…\r\nPişmanlıklarını telafi etme şansın olsaydı, bazı konularda farklı davranır mıydın?*\r\n\r\nNora Seed berbat halde. Kedisi öldü. İşinden kovuldu. Abisi onunla konuşmuyor. Kimsenin ona ihtiyacı yok. Art arda alınmış kötü kararların sonucunda bir kütüphanede buluyor kendini. Zamanın hiç akmadığı bir gece yarısı kütüphanesinde, sonsuz sayıda kitabın ortasında... Kitapların her birinde Nora’nın farklı bir hayatı yazılı. Başka kararlar verseydi yaşamış olabileceği hayatlar.\r\n\r\nFarklı kariyerler, farklı eşler, farklı arkadaşlar, farklı şehirler arasında gidip gelen Nora’nın aklı sorularla doluyor. Mutluluk sadece önemli sandığımız seçimlerde mi gizli? Yanlış giden her detayın sorumlusu gerçekten biz miyiz? Hayatı yaşanılır kılan ne? Yanlış bir karar insanın tüm hayatına mal olabilir mi?",
                            AuthorId = 8,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(830),
                            EditionNumber = 2,
                            EditionYear = 2022,
                            ImageUrl = "gece-yarisi-kutuphanesi.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(830),
                            Name = "Gece Yarısı Kütüphanesi",
                            PageCount = 512,
                            Price = 100m,
                            PublisherId = 5,
                            Stock = 32,
                            Url = "gece-yarisi-kutuphanesi-16"
                        },
                        new
                        {
                            Id = 20,
                            About = "Dünyayı pençesine almış bir delilik salgını...\r\n\r\nKonuşma yoluyla, zihinden zihne bulaşarak yayılan bir hastalık...\r\n\r\nYıkılmanın eşiğine gelmiş uygarlık...\r\n\r\nVaktiyle bu amansız hastalık üzerine çalışmış eski dilbilimci Murat Siyavuş, umutsuzluk içinde annesinin evine sığınmıştır. Acımasız bir devlet kurumunun peşine düştüğünü öğrenince, evden çıkıp hayata karışmak ve salgının dönüştürdüğü dünyayla yüzleşmek zorunda kalır.",
                            AuthorId = 15,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(830),
                            EditionNumber = 2,
                            EditionYear = 2023,
                            ImageUrl = "sicak-kafa.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(830),
                            Name = "Sıcak Kafa",
                            PageCount = 285,
                            Price = 90m,
                            PublisherId = 10,
                            Stock = 40,
                            Url = "sicak-kafa-20"
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.BookCategory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 1,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 13
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 12
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 12,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 12,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 12,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 13,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 13,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 13,
                            CategoryId = 11
                        },
                        new
                        {
                            BookId = 14,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 14,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 14,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 15,
                            CategoryId = 13
                        },
                        new
                        {
                            BookId = 15,
                            CategoryId = 14
                        },
                        new
                        {
                            BookId = 16,
                            CategoryId = 13
                        },
                        new
                        {
                            BookId = 16,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 17,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 17,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 18,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 18,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 19,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 19,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 19,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 20,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 20,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 20,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1910),
                            Description = "Bilim Kurgu Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1910),
                            Name = "Bilim Kurgu",
                            Url = "bilim-kurgu"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1920),
                            Description = "Bilim ve Mühendislik Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1920),
                            Name = "Bilim ve Mühendislik",
                            Url = "bilim-ve-muhendislik"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1920),
                            Description = "Distopya Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1920),
                            Name = "Distopya",
                            Url = "distopya"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1920),
                            Description = "Dünya Tarihi Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1920),
                            Name = "Dünya Tarihi",
                            Url = "dunya-tarihi"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1920),
                            Description = "Edebiyat Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1920),
                            Name = "Edebiyat",
                            Url = "edebiyat"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1930),
                            Description = "Fizik Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1930),
                            Name = "Fizik",
                            Url = "fizik"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1930),
                            Description = "İnsan ve Toplum Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1930),
                            Name = "İnsan ve Toplum",
                            Url = "insan-ve-toplum"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1930),
                            Description = "Kişisel Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1940),
                            Name = "Kişisel Gelişim",
                            Url = "kisisel-gelisim"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1940),
                            Description = "Popüler Bilim Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1940),
                            Name = "Popüler Bilim",
                            Url = "populer-bilim"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1940),
                            Description = "Romanlar",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1940),
                            Name = "Roman",
                            Url = "roman"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1950),
                            Description = "Rus Edebiyatı Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1950),
                            Name = "Rus Edebiyatı",
                            Url = "rus-edebiyati"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1950),
                            Description = "Söyleşi Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1950),
                            Name = "Söyleşi",
                            Url = "soylesi"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1950),
                            Description = "Tarih Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1950),
                            Name = "Tarih",
                            Url = "tarih"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1950),
                            Description = "Türkiye Tarihi Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(1950),
                            Name = "Türkiye Tarihi",
                            Url = "turkiye-tarihi"
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "İstanbul",
                            Country = "Türkiye",
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2870),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2880),
                            Name = "İthaki Yayınları",
                            Phone = "02164785696",
                            Url = "ithaki-yayinlari"
                        },
                        new
                        {
                            Id = 2,
                            City = "İstanbul",
                            Country = "Türkiye",
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2930),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2930),
                            Name = "Alfa Yayınları",
                            Phone = "02164785696",
                            Url = "alfa-yayinlari"
                        },
                        new
                        {
                            Id = 3,
                            City = "İstanbul",
                            Country = "Türkiye",
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2940),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2940),
                            Name = "Can Yayınları",
                            Phone = "02164785696",
                            Url = "can-yayinlari"
                        },
                        new
                        {
                            Id = 4,
                            City = "İstanbul",
                            Country = "Türkiye",
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2940),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2940),
                            Name = "Kronik Yayınevi",
                            Phone = "02164785696",
                            Url = "kronik-yayinevi"
                        },
                        new
                        {
                            Id = 5,
                            City = "İstanbul",
                            Country = "Türkiye",
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2940),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2940),
                            Name = "Domingo Yayınları",
                            Phone = "02164785696",
                            Url = "domingo-yayinlari"
                        },
                        new
                        {
                            Id = 6,
                            City = "İstanbul",
                            Country = "Türkiye",
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2940),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2950),
                            Name = "Epsilon Yayınları",
                            Phone = "02164785696",
                            Url = "epsilon-yayinlari"
                        },
                        new
                        {
                            Id = 7,
                            City = "İstanbul",
                            Country = "Türkiye",
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2950),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2950),
                            Name = "Nemesis",
                            Phone = "02164785696",
                            Url = "nemesis-kitap"
                        },
                        new
                        {
                            Id = 8,
                            City = "İstanbul",
                            Country = "Türkiye",
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2950),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2950),
                            Name = "İş Bankası Kültür Yayınları",
                            Phone = "02164785696",
                            Url = "is-bankasi-kultur-yayinlari"
                        },
                        new
                        {
                            Id = 9,
                            City = "İstanbul",
                            Country = "Türkiye",
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2950),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2950),
                            Name = "Yediveren Yayınları",
                            Phone = "02164785696",
                            Url = "yediveren-yayinlari"
                        },
                        new
                        {
                            Id = 10,
                            City = "İstanbul",
                            Country = "Türkiye",
                            CreatedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2950),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 22, 13, 26, 8, 112, DateTimeKind.Local).AddTicks(2960),
                            Name = "April Yayıncılık",
                            Phone = "02164785696",
                            Url = "april-yayincilik"
                        });
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Book", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BooksApp.Entity.Concrete.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.BookCategory", b =>
                {
                    b.HasOne("BooksApp.Entity.Concrete.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksApp.Entity.Concrete.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Book", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Category", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("BooksApp.Entity.Concrete.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
